# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1e5b2f899b5b260e0d12eba1d17a4e01460e1aecab2192ec8073beeef8c7f1517ef9a43e63185fd4d2fca262dbc47fc8321b22d71035a0eb914ee297c2d99e38

test:
  secret_key_base: e5a62d8063c384b0a8699a85817aa3734993454c058f6f6338fd60124867ad529f35dcd4848e2e5b7c616dcdfcbf67c002e1830a32344c0dd24dd4f12221229f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
